apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-vol
  annotations:
    argocd.argoproj.io/sync-wave: '-2'
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
