apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  SECRET_KEY: changethis
  FIRST_SUPERUSER_PASSWORD: changethis
  SMTP_PASSWORD: ""
  POSTGRES_PASSWORD: changethis
