apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap-backend.yaml
  - configmap-db.yaml
  - configmap-frontend.yaml
  - pvc-db.yaml
  - deployment-backend.yaml
  - service-backend.yaml
  - deployment-db.yaml
  - service-db.yaml
  - deployment-frontend.yaml
  - service-frontend.yaml
  - deployment-adminer.yaml
  - service-adminer.yaml
  - job-prestart.yaml
  - ingress-app.yaml

images:
  - name: backend
    newName: ghcr.io/fastapi-traefik-devops/fastapi-backend
    newTag: v0.1.0
  - name: frontend
    newName: ghcr.io/fastapi-traefik-devops/fastapi-frontend
    newTag: v0.1.0
