apiVersion: batch/v1
kind: Job
metadata:
  name: prestart
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: prestart
          image: backend:latest
          command: ["bash", "scripts/prestart.sh"]
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
