---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secrets
  namespace: dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCVtZOP1cZDzkNF/tuychDQPy0vzJ3C0dJg6sf9GJqpO9JDnnB//EYLZIoBhU2HPBMMOVcLT+/jTK0/DlEdvSIn7kHvVDqBuwVdjqO8rHKKp9ycXqzsMqUBd98ZKpT4161tZOqLdxqV7wrdhV+Vsl4rLCgwA+Evgz0UmljkNVGSPXXyjn25aOHP5RoTWRO4Shqgx27MLHmA1LPW8DKnT6uc1u97NQt2dv03fV7SkoOqldV/OsmQosfDdjhzwU3+Jx78bllf6/D++YDs6epeNVt/5SiP3Pjil4OXyzDU8D/7iHYNmMUn68vk9g+hyJE3F49XexpMcMjulemphZkmc0OEEpCWU3r7Pqc4hiV927YzXc2iMaXjeW4bcG62h5WpeUArV1o2hWqbzw+0eSihwtSGioVBH3PLHW4euIu+K27KiJ0XTsuZA1YrfO00CnMT32GWR4/TClHSM0rPqNQBY7SEp0lRuRpozH8Ameq8H1W7mrmSXDO7fnlLC6Y8XtiWpSjiIFyoHtwPDm5JDkG+hGaDEyZN19KQFC5SMZ407FBqxAFsPqH0mL2g53ZuFNR5M0Q3nyQ6c8DcY7lz8e5SOlzSuSNo0Vbr/WQEuts3gjAv6nkxgmZTxqXiKOheQJCdO36sAtkbvX27iK+yBlpIHTxo1ZJG7wb6n8W3+rA9HCRnYmC5C93JZ0R2JrVlF+gZ63UIRCPhtzudxTfCwlCIT3Muxgo+INqvQSdCFIdAJDj0NX6YX8L6GQ==
  template:
    metadata:
      name: db-secrets
      namespace: dev
